classdef c_EME < c_lumBaseObject
% Lumerical EME simulation object
% 
% author: bohan
%
% List of properties of the lumerical object
% returned when called ?set; on an EME object:
% actual mesh cells x
% actual mesh cells y
% actual mesh cells z
% add material gain to maximum tolerated gain
% additional pml mode factor
% algorithm
% allow custom eigensolver settings
% allow symmetry on all boundaries
% background index
% cells
% center frequency
% center wavelength
% conformal meshing refinement
% convergence tolerance
% correct backward propagating modes
% correct backward propagating modes when pml is present
% define x mesh by
% define y mesh by
% define z mesh by
% display cells
% dx
% dy
% dz
% enabled
% end cell group
% energy conservation
% fit analytic materials
% fit materials with multi-coefficient model
% fit sampled materials
% force symmetric x mesh
% force symmetric y mesh
% force symmetric z mesh
% fractional offset for group delay
% frequency
% frequency span
% frequency start
% frequency stop
% grading factor
% group spans
% interfaces
% max stored modes
% maximum tolerated gain
% mesh cells x
% mesh cells y
% mesh cells z
% mesh refinement
% meshing refinement
% meshing tolerance
% min mesh step
% modes
% name
% number of cell groups
% number of modes for all cell groups
% number of periodic groups
% periods
% pml kappa
% pml layers
% pml polynomial
% pml sigma
% simulation temperature
% solver type
% start
% start cell group
% stop
% subcell method
% tolerance 1
% tolerance 2
% tolerance 3
% type
% use legacy conformal interface detection
% use mesh refinement
% use relative coordinates
% wavelength
% wavelength span
% wavelength start
% wavelength stop
% x
% x max
% x max bc
% x min
% x min bc
% x span
% y
% y max
% y max bc
% y min
% y min bc
% y span
% z
% z max
% z max bc
% z min
% z min bc
% z span
    
    properties
        
        model_type;
        name; 

    end     % end properties
    
    
    methods
        
        function obj = c_EME( varargin )
            % constructor
            %
            % inputs:
            %   varargin = name value pairs
            %           where name must be one of the valid props
            
            % valid property names
            valid_props =   {
                            'actual mesh cells x', ...
                            'actual mesh cells y', ...
                            'actual mesh cells z', ...
                            'add material gain to maximum tolerated gain', ...
                            'additional pml mode factor', ...
                            'algorithm', ...
                            'allow custom eigensolver settings', ...
                            'allow symmetry on all boundaries', ...
                            'background index', ...
                            'cells', ...
                            'center frequency', ...
                            'center wavelength', ...
                            'conformal meshing refinement', ...
                            'convergence tolerance', ...
                            'correct backward propagating modes', ...
                            'correct backward propagating modes when pml is present', ...
                            'define x mesh by', ...
                            'define y mesh by', ...
                            'define z mesh by', ...
                            'display cells', ...
                            'dx', ...
                            'dy', ...
                            'dz', ...
                            'enabled', ...
                            'end cell group', ...
                            'energy conservation', ...
                            'fit analytic materials', ...
                            'fit materials with multi-coefficient model', ...
                            'fit sampled materials', ...
                            'force symmetric x mesh', ...
                            'force symmetric y mesh', ...
                            'force symmetric z mesh', ...
                            'fractional offset for group delay', ...
                            'frequency', ...
                            'frequency span', ...
                            'frequency start', ...
                            'frequency stop', ...
                            'grading factor', ...
                            'group spans', ...
                            'interfaces', ...
                            'max stored modes', ...
                            'maximum tolerated gain', ...
                            'mesh cells x', ...
                            'mesh cells y', ...
                            'mesh cells z', ...
                            'mesh refinement', ...
                            'meshing refinement', ...
                            'meshing tolerance', ...
                            'min mesh step', ...
                            'modes', ...
                            'name', ...
                            'number of cell groups', ...
                            'number of modes for all cell groups', ...
                            'number of periodic groups', ...
                            'periods', ...
                            'pml kappa', ...
                            'pml layers', ...
                            'pml polynomial', ...
                            'pml sigma', ...
                            'simulation temperature', ...
                            'solver type', ...
                            'start', ...
                            'start cell group', ...
                            'stop', ...
                            'subcell method', ...
                            'tolerance 1', ...
                            'tolerance 2', ...
                            'tolerance 3', ...
                            'type', ...
                            'use legacy conformal interface detection', ...
                            'use mesh refinement', ...
                            'use relative coordinates', ...
                            'wavelength', ...
                            'wavelength span', ...
                            'wavelength start', ...
                            'wavelength stop', ...
                            'x', ...
                            'x max', ...
                            'x max bc', ...
                            'x min', ...
                            'x min bc', ...
                            'x span', ...
                            'y', ...
                            'y max', ...
                            'y max bc', ...
                            'y min', ...
                            'y min bc', ...
                            'y span', ...
                            'z', ...
                            'z max', ...
                            'z max bc', ...
                            'z min', ...
                            'z min bc', ...
                            'z span' ...
                            };
            
            obj = obj@c_lumBaseObject( valid_props, varargin{:} );
                        
            obj.model_type = 'EME';
            
        end     % end constructor()
        

    end     % end methods
    
end





































