classdef c_FDTD < c_lumBaseObject
% Lumerical finite difference time domain solver region object
% Specific to FDTD solutions
% 
% author: bohan
%
% List of properties of the lumerical object
% returned when called ?set; on a FDTD model object:
% allow grading in x
% allow grading in y
% allow grading in z
% allow symmetry on all boundaries
% always use complex fields
% angle phi
% angle theta
% auto shutoff max
% auto shutoff min
% background index
% bfast alpha
% bfast dt multiplier
% bloch units
% define x mesh by
% define y mesh by
% define z mesh by
% dimension
% direction
% down sample time
% dt
% dt stability factor
% dx
% dy
% dz
% enabled
% extend structure through pml
% force symmetric x mesh
% force symmetric y mesh
% force symmetric z mesh
% grading factor
% injection axis
% kx
% ky
% kz
% max source time signal length
% mesh accuracy
% mesh cells per wavelength
% mesh cells x
% mesh cells y
% mesh cells z
% mesh frequency max
% mesh frequency min
% mesh refinement
% mesh type
% mesh wavelength max
% mesh wavelength min
% meshing refinement
% min mesh step
% name
% nx
% ny
% nz
% override simulation bandwidth for mesh generation
% param1
% param2
% pml alpha
% pml alpha polynomial
% pml kappa
% pml layers
% pml max layers
% pml min layers
% pml polynomial
% pml profile
% pml sigma
% pml type
% same settings on all boundaries
% set based on source angle
% set process grid
% set simulation bandwidth
% simulation frequency max
% simulation frequency min
% simulation temperature
% simulation time
% simulation wavelength max
% simulation wavelength min
% snap pec to yee cell boundary
% source_index
% type
% use auto shutoff
% use bfast fdtd
% use divergence checking
% use early shutoff
% use relative coordinates
% x
% x max
% x max bc
% x min
% x min bc
% x span
% y
% y max
% y max bc
% y min
% y min bc
% y span
% z
% z max
% z max bc
% z min
% z min bc
% z span
    
    properties
        
        model_type;
        name;          

    end     % end properties
    
    
    methods
        
        function obj = c_FDTD( varargin )
            % constructor
            %
            % inputs:
            %   varargin = name value pairs
            %           where name must be one of the valid props
            
            % valid property names
            valid_props =   { ...
                            'allow grading in x', ...
                            'allow grading in y', ...
                            'allow grading in z', ...
                            'allow symmetry on all boundaries', ...
                            'always use complex fields', ...
                            'angle phi', ...
                            'angle theta', ...
                            'auto shutoff max', ...
                            'auto shutoff min', ...
                            'background index', ...
                            'bfast alpha', ...
                            'bfast dt multiplier', ...
                            'bloch units', ...
                            'define x mesh by', ...
                            'define y mesh by', ...
                            'define z mesh by', ...
                            'dimension', ...
                            'direction', ...
                            'down sample time', ...
                            'dt', ...
                            'dt stability factor', ...
                            'dx', ...
                            'dy', ...
                            'dz', ...
                            'enabled', ...
                            'extend structure through pml', ...
                            'force symmetric x mesh', ...
                            'force symmetric y mesh', ...
                            'force symmetric z mesh', ...
                            'grading factor', ...
                            'index', ...
                            'injection axis', ...
                            'kx', ...
                            'ky', ...
                            'kz', ...
                            'max source time signal length', ...
                            'mesh accuracy', ...
                            'mesh cells per wavelength', ...
                            'mesh cells x', ...
                            'mesh cells y', ...
                            'mesh cells z', ...
                            'mesh frequency max', ...
                            'mesh frequency min', ...
                            'mesh refinement', ...
                            'mesh type', ...
                            'mesh wavelength max', ...
                            'mesh wavelength min', ...
                            'meshing refinement', ...
                            'min mesh step', ...
                            'name', ...
                            'nx', ...
                            'ny', ...
                            'nz', ...
                            'override simulation bandwidth for mesh generation', ...
                            'param1', ...
                            'param2', ...
                            'pml alpha', ...
                            'pml alpha polynomial', ...
                            'pml kappa', ...
                            'pml layers', ...
                            'pml max layers', ...
                            'pml min layers', ...
                            'pml polynomial', ...
                            'pml profile', ...
                            'pml sigma', ...
                            'pml type', ...
                            'same settings on all boundaries', ...
                            'set based on source angle', ...
                            'set process grid', ...
                            'set simulation bandwidth', ...
                            'simulation frequency max', ...
                            'simulation frequency min', ...
                            'simulation temperature', ...
                            'simulation time', ...
                            'simulation wavelength max', ...
                            'simulation wavelength min', ...
                            'snap pec to yee cell boundary', ...
                            'source_index', ...
                            'type', ...
                            'use auto shutoff', ...
                            'use bfast fdtd', ...
                            'use divergence checking', ...
                            'use early shutoff', ...
                            'use relative coordinates', ...
                            'x', ...
                            'x max', ...
                            'x max bc', ...
                            'x min', ...
                            'x min bc', ...
                            'x span', ...
                            'y', ...
                            'y max', ...
                            'y max bc', ...
                            'y min', ...
                            'y min bc', ...
                            'y span', ...
                            'z', ...
                            'z max', ...
                            'z max bc', ...
                            'z min', ...
                            'z min bc', ...
                            'z span'...
                            };
            
            obj = obj@c_lumBaseObject( valid_props, varargin{:} );
                        
            obj.model_type  = 'FiniteDifferenceTimeDomainSolver';
            obj.name        = 'FDTD';
            
        end     % end constructor()
        

    end     % end methods
    
end






































